version: "3"
services:
  airflow:
    build: airflow/
    container_name: airflow
    networks:
      dmls:
        #ipv4_address: "172.28.0.5"
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags

  postgres:
    image: postgres:14
    container_name: postgres
    depends_on:
      - airflow
    networks:
      dmls:
        #ipv4_address: "172.28.0.10"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: MYZv3Ietuflo
      POSTGRES_USER: postgres
      POSTGRES_DB: airflow
    healthcheck:
      test: pg_isready || echo 1
      interval: 3s
      timeout: 2s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      
  superset:
    image: apache/superset:master
    container_name: superset
    depends_on:
      - airflow
    networks:
      dmls:
        #ipv4_address: "172.28.0.10"
    ports:
      - "8088:8088"
    volumes:
      - ./superset/:/app/superset_home
      
  jupyter:
    build: jupyter/
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "teR5vHZhDddq"
    volumes:
      - /home/ivan_admin/dmls_aviaticket/ipynb:/home/jovyan
      - /home/ivan_admin/dmls_aviaticket/airflow/dags:/home/jovyan/dags
    networks:
      dmls:
    
    mlflow:
    build: mlflow/
    container_name: mlflow
    ports:
      - "7999:7999"
    networks:
      dmls:
      
networks:
  dmls:
    ipam:
      driver: default
      #config:
      #  - subnet: "172.28.0.0/24"
