# Возьмем за основу образ 
FROM python:3.10.9

# Airflow глобальные переменные
ARG AIRFLOW_VERSION=2.5.0
ARG MAJOR_PYTHON_VERSION=3.10
ARG CONSTRAINT_URL=https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${MAJOR_PYTHON_VERSION}.txt

ARG AIRFLOW_USER_HOME=/usr/local/airflow
ENV AIRFLOW_HOME=${AIRFLOW_USER_HOME}

# Сборка airflow
RUN pip install --upgrade pip
RUN pip install apache-airflow[postgres]==${AIRFLOW_VERSION} --constraint ${CONSTRAINT_URL}
#RUN pip install pandas
#RUN pip install SQLAlchemy==1.3.23
#RUN pip install markupsafe==2.0.1
#RUN pip install wtforms==2.3.3
#RUN pip install flask-bcrypt

# Создаем директрию для скриптов
#RUN mkdir /project

# Копируем скрипты и конфиг файл
#COPY script/ /project/scripts/
#COPY config/airflow.cfg ${AIRFLOW_HOME}/airflow.cfg

# Доступы для скрипта
#RUN chmod +x /project/scripts/*

# Запускаем airflow
ENTRYPOINT airflow standalone


# CMD ["python", "/project/scripts/auth.py"]

#sudo docker-compose build --no-cache && docker-compose --env-file .envrc up -d
